### ISSUE TITLE
Stay on current page when I switch LÖVR versions

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr.org#6]
If I'm looking at https://lovr.org/docs/Pass and I switch to `master`, I'd love to go to https://lovr.org/docs/master/Pass instead of https://lovr.org/docs/master/Getting_Started. 

This would make it easier to compare API differences between versions.

**Comment by bjornbytes** [comment]
Fixed in #8 / 2f7aaf20c09511b5abbe527081c9eeaf6242c750
